### ISSUE TITLE
Workerが落ちないことがある

### ISSUE THREAD

**Issue by ktateish** [penguin-judge/PenguinJudge#176]
systemd から `ExecStart=docker run ... worker` で起動していた場合、 `systemctl restart worker` で worker のコンテナがうまく停止せず、 docker ps で見ると残ったままになってしまうことがある。

再現条件はよくわかっていないが、提出コードを1回以上ジャッジすると発生しやすいようだ。（1回もジャッジしてない worker では今の所発生しない）

落ちなかったときのログは以下。

```
-- Unit worker.service has begun shutting down.
May 21 11:18:07 worker-01 docker[9334]: Exception in thread QueueManagerThread:
May 21 11:18:07 worker-01 docker[9334]: Traceback (most recent call last):
May 21 11:18:07 worker-01 docker[9334]:   File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
May 21 11:18:07 worker-01 docker[9334]:     self.run()
May 21 11:18:07 worker-01 docker[9334]:   File "/usr/local/lib/python3.7/threading.py", line 870, in run
May 21 11:18:07 worker-01 docker[9334]:     self._target(*self._args, **self._kwargs)
May 21 11:18:07 worker-01 docker[9334]:   File "/usr/local/lib/python3.7/concurrent/futures/process.py", line 375, in _queue_management_worker
May 21 11:18:07 worker-01 docker[9334]:     thread_wakeup.clear()
May 21 11:18:07 worker-01 docker[9334]:   File "/usr/local/lib/python3.7/concurrent/futures/process.py", line 94, in clear
May 21 11:18:07 worker-01 docker[9334]:     self._reader.recv_bytes()
May 21 11:18:07 worker-01 docker[9334]:   File "/usr/local/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
May 21 11:18:07 worker-01 docker[9334]:     buf = self._recv_bytes(maxlength)
May 21 11:18:07 worker-01 docker[9334]:   File "/usr/local/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
May 21 11:18:07 worker-01 docker[9334]:     buf = self._recv(4)
May 21 11:18:07 worker-01 docker[9334]:   File "/usr/local/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
May 21 11:18:07 worker-01 docker[9334]:     raise EOFError
May 21 11:18:07 worker-01 docker[9334]: EOFError
```

正常に落ちてくれるときは次のようなログがでる
```
-- Unit worker.service has begun shutting down.
May 21 11:45:52 worker-01 docker[14116]: Traceback (most recent call last):
May 21 11:45:52 worker-01 docker[14116]:   File "/usr/local/bin/penguin_judge", line 8, in <module>
May 21 11:45:52 worker-01 docker[14116]:     sys.exit(main())
May 21 11:45:52 worker-01 docker[14116]:   File "/usr/local/lib/python3.7/site-packages/penguin_judge/main.py", line 97, in main
May 21 11:45:52 worker-01 docker[14116]:     args.start(args)
May 21 11:45:52 worker-01 docker[14116]:   File "/usr/local/lib/python3.7/site-packages/penguin_judge/main.py", line 75, in start_worker
May 21 11:45:52 worker-01 docker[14116]:     worker_main(get_db_config(), max_processes)
May 21 11:45:52 worker-01 docker[14116]:   File "/usr/local/lib/python3.7/site-packages/penguin_judge/worker.py", line 247, in main
May 21 11:45:52 worker-01 docker[14116]:     worker.start()
May 21 11:45:52 worker-01 docker[14116]:   File "/usr/local/lib/python3.7/site-packages/penguin_judge/worker.py", line 58, in start
May 21 11:45:52 worker-01 docker[14116]:     asyncio.get_event_loop().run_forever()
May 21 11:45:52 worker-01 docker[14116]:   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
May 21 11:45:52 worker-01 docker[14116]:     self._run_once()
May 21 11:45:52 worker-01 docker[14116]:   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1750, in _run_once
May 21 11:45:52 worker-01 docker[14116]:     event_list = self._selector.select(timeout)
May 21 11:45:52 worker-01 docker[14116]:   File "/usr/local/lib/python3.7/selectors.py", line 468, in select
May 21 11:45:52 worker-01 docker[14116]:     fd_event_list = self._selector.poll(timeout, max_ev)
May 21 11:45:52 worker-01 docker[14116]: KeyboardInterrupt
May 21 11:45:52 worker-01 systemd[1]: worker.service: Main process exited, code=exited, status=1/FAILURE
May 21 11:45:52 worker-01 systemd[1]: worker.service: Failed with result 'exit-code'.
May 21 11:45:52 worker-01 systemd[1]: Stopped Penguin Worker Daemon.
```

**Comment by ktateish** [comment]
ログを見直していたら、事象発生時にまったくログがでていないケースもあったので、↑のログは関係ないかもしれません

```
May 21 11:46:30 worker-02 systemd[1]: Stopping Penguin Worker Daemon...
-- Subject: Unit worker.service has begun shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit worker.service has begun shutting down.
May 21 11:48:00 worker-02 systemd[1]: worker.service: State 'stop-sigterm' timed out. Killing.
May 21 11:48:00 worker-02 systemd[1]: worker.service: Killing process 10008 (docker) with signal SIGKILL.
May 21 11:48:00 worker-02 systemd[1]: worker.service: Main process exited, code=killed, status=9/KILL
May 21 11:48:00 worker-02 systemd[1]: worker.service: Failed with result 'timeout'.
May 21 11:48:00 worker-02 systemd[1]: Stopped Penguin Worker Daemon.
-- Subject: Unit worker.service has finished shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit worker.service has finished shutting down.
May 21 11:48:00 worker-02 systemd[1]: Starting Penguin Worker Daemon...
```
